---
version: 2
jobs:
  JRuby 9.2.8.0, JDK 8 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.2.8.0-8-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.8.0, JDK 8:
    docker:
    - image: fidothe/circleci:jruby-9.2.8.0-8-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Install Code Climate Test Reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
    - run:
        name: Run the tests, and upload coverage data to Code Climate
        command: |-
          ./cc-test-reporter before-build
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
          ./cc-test-reporter after-build -t simplecov --exit-code=$?
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.8.0, JDK 11 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.2.8.0-11-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.8.0, JDK 11:
    docker:
    - image: fidothe/circleci:jruby-9.2.8.0-11-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.8.0, JDK 13 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.2.8.0-13-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.8.0, JDK 13:
    docker:
    - image: fidothe/circleci:jruby-9.2.8.0-13-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.1.17.0, JDK 8 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.1.17.0-8-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.1.17.0, JDK 8:
    docker:
    - image: fidothe/circleci:jruby-9.1.17.0-8-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.1.17.0, JDK 11 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.1.17.0-11-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.1.17.0, JDK 11:
    docker:
    - image: fidothe/circleci:jruby-9.1.17.0-11-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.1.17.0, JDK 13 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.1.17.0-13-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.1.17.0, JDK 13:
    docker:
    - image: fidothe/circleci:jruby-9.1.17.0-13-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.9.0-SNAPSHOT-latest, JDK 8 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.2.9.0-SNAPSHOT-latest-8-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.9.0-SNAPSHOT-latest, JDK 8:
    docker:
    - image: fidothe/circleci:jruby-9.2.9.0-SNAPSHOT-latest-8-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.9.0-SNAPSHOT-latest, JDK 11 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.2.9.0-SNAPSHOT-latest-11-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.9.0-SNAPSHOT-latest, JDK 11:
    docker:
    - image: fidothe/circleci:jruby-9.2.9.0-SNAPSHOT-latest-11-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.9.0-SNAPSHOT-latest, JDK 13 Saxon HE 9.8:
    docker:
    - image: fidothe/circleci:jruby-9.2.9.0-SNAPSHOT-latest-13-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
      ALTERNATE_SAXON_HOME: "/tmp/saxon"
    steps:
    - checkout
    - run:
        name: Download SaxonHE9-8-0-15J.zip
        command: |-
          mkdir -p /tmp/workspace/saxon
          cd /tmp/workspace/saxon
          curl -L -O https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-15J.zip
          unzip SaxonHE9-8-0-15J.zip
          rm -f SaxonHE9-8-0-15J.zip
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
  JRuby 9.2.9.0-SNAPSHOT-latest, JDK 13:
    docker:
    - image: fidothe/circleci:jruby-9.2.9.0-SNAPSHOT-latest-13-jdk-slim
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      JRUBY_OPTS: "--dev --debug"
    steps:
    - checkout
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - run:
        name: Run the tests
        command: |-
          mkdir -p /tmp/test-results
          bundle exec rspec spec --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - store_test_results:
        path: "/tmp/test-results"
    - store_artifacts:
        path: "/tmp/test-results"
        destination: test-results
workflows:
  version: 2
  build_and_test:
    jobs:
    - JRuby 9.2.8.0, JDK 8 Saxon HE 9.8
    - JRuby 9.2.8.0, JDK 8
    - JRuby 9.2.8.0, JDK 11 Saxon HE 9.8
    - JRuby 9.2.8.0, JDK 11
    - JRuby 9.2.8.0, JDK 13 Saxon HE 9.8
    - JRuby 9.2.8.0, JDK 13
    - JRuby 9.1.17.0, JDK 8 Saxon HE 9.8
    - JRuby 9.1.17.0, JDK 8
    - JRuby 9.1.17.0, JDK 11 Saxon HE 9.8
    - JRuby 9.1.17.0, JDK 11
    - JRuby 9.1.17.0, JDK 13 Saxon HE 9.8
    - JRuby 9.1.17.0, JDK 13
    - JRuby 9.2.9.0-SNAPSHOT-latest, JDK 8 Saxon HE 9.8
    - JRuby 9.2.9.0-SNAPSHOT-latest, JDK 8
    - JRuby 9.2.9.0-SNAPSHOT-latest, JDK 11 Saxon HE 9.8
    - JRuby 9.2.9.0-SNAPSHOT-latest, JDK 11
    - JRuby 9.2.9.0-SNAPSHOT-latest, JDK 13 Saxon HE 9.8
    - JRuby 9.2.9.0-SNAPSHOT-latest, JDK 13
